### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by naveenkrdy** [lvs1974/CpuTscSync#2]
Hi ! 
first of all amazing work. !

i have an issue where AMD CPU's like Threadripper 1950x, 2950x etc, panics randomly.
Can a basic support for AMD be added to this kext to sync TSC.
https://github.com/RehabMan/VoodooTSCSync/tree/37d7c5869a9b3f42b188b2242bc13f05d75bc9e2/AMD

[panic.txt](https://github.com/lvs1974/CpuTscSync/files/4974191/panic.txt)

Thanks !

**Comment by naveenkrdy** [comment]
@lvs1974 
[message.txt](https://github.com/lvs1974/CpuTscSync/files/5004390/message.txt)

**Comment by lvs1974** [comment]
@naveenkrdy, Hi!
The best way of implementing this would be another kext - AmdCpuTscSync.
I will try to do this on next week.

**Comment by naveenkrdy** [comment]
> @naveenkrdy, Hi!
> The best way of implementing this would be creation of another kext - AmdCpuTscSync.
> I will try to do this on next week.

thanks ! for your work.

**Comment by lvs1974** [comment]
@naveenkrdy, I had a look at attached panics, and  I can say that CpuTscSync will not help (even if I adapt code for syncing cpus every 10 milliseconds). CpuTscSync can help only when Intel CPU Power Management is used, since it blocks execution of xcpm_urgency, and this method is not in any backtraces. Most probably it is not called at all for AMD.
I wrote this case to fix random panics happened during awake/hibernation resume phases.
If AMD-adapted version of VoodooTscSync does not help (at least it should be stable without sleep/awake/hibernation resume), I have no idea how to fix it. It looks like there is an issue with spin locks and NMI.

**Comment by naveenkrdy** [comment]
@lvs1974 thanks for looking into it, much appreciated . 
the second panic was with VoodooTSCSyncAMD and t seems to be much stable than before but panic still happend later after a while.

**Comment by naveenkrdy** [comment]
@lvs1974 i have a doubt ! 
the tsc needs to be synced every 10 milliseconds or in seconds ?

**Comment by lvs1974** [comment]
@naveenkrdy, in VoodoiTscSyncit is synced only after wake. In AMD version from Rehab it is synced by timer every 10 seconds.

**Comment by naveenkrdy** [comment]
> @naveenkrdy, in VoodoiTscSyncit is synced only after wake. In AMD version from Rehab it is synced by timer every 10 seconds.

thanks for the info !

**Comment by lvs1974** [comment]
@naveenkrdy, could you try an attached kext, please?
[VoodooTSCSyncAMD.kext.zip](https://github.com/lvs1974/CpuTscSync/files/5021938/VoodooTSCSyncAMD.kext.zip)

**Comment by naveenkrdy** [comment]
@lvs1974 
Hi ! hope you are doing good. 
I tried booting with it and it panicked.
![0EA88F2B-D263-4E05-9970-05621466C512](https://user-images.githubusercontent.com/18463250/89320691-6a501a00-d69f-11ea-8203-e65d463991ca.jpeg)

looks like probe function is causing this issue ?

Thanks !

**Comment by lvs1974** [comment]
@naveenkrdy, how many threads does your CPU have?

**Comment by naveenkrdy** [comment]
@lvs1974 16 cores 32 threads.

**Comment by lvs1974** [comment]
@naveenkrdy: 
[VoodooTSCSyncAMD.kext.zip](https://github.com/lvs1974/CpuTscSync/files/5023742/VoodooTSCSyncAMD.kext.zip)

**Comment by naveenkrdy** [comment]
@lvs1974 no panic : )
booted fine.

**Comment by lvs1974** [comment]
@naveenkrdy: if it works, could you try this version, please: 
[VoodooTSCSyncAMD.kext.zip](https://github.com/lvs1974/CpuTscSync/files/5024306/VoodooTSCSyncAMD.kext.zip)

**Comment by naveenkrdy** [comment]
> @naveenkrdy: if it works, could you try this version, please:
> [VoodooTSCSyncAMD.kext.zip](https://github.com/lvs1974/CpuTscSync/files/5024306/VoodooTSCSyncAMD.kext.zip)

will do and report back : )
just one doubt. i see you added back the `IOCPUNumber` back and the value is 32 
shouldn't it be 31 ? as 32-1 ?

**Comment by lvs1974** [comment]
@naveenkrdy, you are right, it should be 31. Please check it with 31.

If this kext works, can you also build VoodooTSCSyncAMD.kext from RehabMan repository, set IOCPUNumber to 31 and check this kext?

**Comment by naveenkrdy** [comment]
@lvs1974 will do thanks !

**Comment by naveenkrdy** [comment]
@lvs1974 Hi !
Tested the above kext on (AMD Threadripper 2990WX ) 64 threads cpu and it booted fine : ) . Also compiled and tested the [VoodooTSCSync](https://github.com/RehabMan/VoodooTSCSync/tree/37d7c5869a9b3f42b188b2242bc13f05d75bc9e2) from rehabman repo and that also booted fine.

**Comment by lvs1974** [comment]
@naveenkrdy: so, it means you just used this RehabMan's kext improperly.
You have to set IOCPUNumber to the last thread of your CPU.
To check whether it is working: after syncing (use debug version of kext to see it) you should not see this line in system log:
"Unsynchronized  TSC for cpu".

**Comment by naveenkrdy** [comment]
@lvs1974 i always set the IOCPUNumber to last thread i.e 31 if on 1950X and 63 if on 2990WX.
and yea i did saw `Unsynchronized TSC for cpu` message in the log before on 2990WX . now it doesn't show anymore.
thanks !
Any way to make that kext automatically attach to last thread on AMD ?

**Comment by lvs1974** [comment]
@naveenkrdy: it is a good idea, but I cannot find out how to read the number of threads for AMD CPU.

**Comment by naveenkrdy** [comment]
@lvs1974 will this help ?
https://github.com/acidanthera/OpenCorePkg/blob/e5f086c779db41812b9e12b903006783f619b4a1/Library/OcCpuLib/OcCpuLib.c#L529
https://github.com/acidanthera/OpenCorePkg/blob/e5f086c779db41812b9e12b903006783f619b4a1/Library/OcCpuLib/OcCpuLib.c#L556

**Comment by lvs1974** [comment]
@naveenkrdy: I think would be better if you could to contact to @trulyspinach. He has already a big repository dedicated to AMD processors and I think it would make sense to add there also  CpuTscSyncAMD.kext with auto-detection of thread numbers.

**Comment by naveenkrdy** [comment]
@lvs1974 thanks ! will do.
closing this issue.
